### ISSUE TITLE
Add a "Back" button when viewing AUs

### ISSUE THREAD

**Issue by FlorianTolk** [adlnet/cmi5-player-moodle-plugin#15]
**Is your feature request related to a problem? Please describe.**
Currently, when you view your attempts in an AU, you do not have a way to go back to the AU list

**Describe the solution you'd like**
A button on the top left of the table that takes the user back to the AU list of the cmi5 package activity

**Comment by ADLMeganBohland** [comment]
The back button has been added and tested. Again, I cannot push to server do to current code freeze but it is here
![image](https://github.com/adlnet/cmi5-player-moodle-plugin/assets/99821412/04b6fae1-7b7d-45c4-9c2e-dd9de2aba12f)

If this is what was in mind we can close out ticket?

**Comment by ADLMeganBohland** [comment]
The code freeze was lifted and change applied
