### ISSUE TITLE
string indentifiers should be in lower case

### ISSUE THREAD

**Issue by danmarsden** [adlnet/cmi5-player-moodle-plugin#27]
https://github.com/adlnet/cmi5-player-moodle-plugin/blob/Development/lang/en/cmi5launch.php#L117-L120

string indentifiers should all be in lower case..

This is probably a blocker for approval as it might cause problems with the AMOS translation tool used by Moodle.

**Comment by ADLMeganBohland** [comment]
@danmarsden Fixed, thank you!
